version: "3.8"

services:
  app:
    image: loyalty_program
    container_name: loyalty_program_app
    env_file: ".env"
    environment:
      - POSTGRESS_HOST=db
      - POSTGRESS_PORT=5432
      - POSTGRESS_NAME=crud
      - POSTGRESS_USER=pg
      - POSTGRESS_PASSWORD=password
      - POSTGRESS_SSL=disable
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: loyalty_program_db
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crud
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
